version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: olaclick-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: olaclick
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - olaclick-network

  redis:
    image: redis:7-alpine
    container_name: olaclick-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - olaclick-network

  app:
    build: .
    container_name: olaclick-app
    restart: unless-stopped
    ports:
      - '3000:3000'
    depends_on:
      - postgres
      - redis
    networks:
      - olaclick-network
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  postgres_data:
  redis_data:

networks:
  olaclick-network:
    driver: bridge
